name: Build Tauri App for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          setx PATH "$env:USERPROFILE\.bun\bin;$env:PATH"

      - name: Install dependencies with bun
        run: bun install

      - name: Install Tauri CLI
        run: npx tauri --version

      - name: Build Tauri app
        run: npx tauri build