name: Build Tauri App for Windows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tauri-ci-win.yml'
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # set BUILD_KEY auto run 
      - name: Set build type
        id: build-type
        run: |
          if (Test-Path env:BUILD_KEY) {
            echo "Using signing key"
            echo "HAS_KEY=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "Building without signing key"
            echo "HAS_KEY=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
        env:
          BUILD_KEY: ${{ secrets.BUILD_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun on Windows
        shell: pwsh
        run: |
          irm https://bun.sh/install.ps1 | iex
          echo "$HOME\.bun\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Install dependencies bun
        run: bun install

      - name: Check Tauri version
        run: bun tauri --version

      - name: Build Rust app with bun
        run: bun tauri build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MCP-Linker-Windows-CI
          path: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi