name: Tauri Release Windows

on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/tauri-release-win.yml'
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
  workflow_dispatch: # Allow manual trigger in GitHub UI

jobs:
  release:
    name: Release on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: MCP-Linker-Windows
          path: dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}